[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TrackingToolBox"
authors = [{name = "Shawn Chen", email = "solairechen@sjtu.edu.cn"}]
dynamic = ["version", "description"]
